name: Build Expo APK

on:
  workflow_dispatch:  # permite rodar manualmente pelo botão "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0

      - name: Install dependencies
        run: |
          npm install -g expo-cli eas-cli
          npm install

      - name: Login to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas whoami || eas login --token $EXPO_TOKEN

      - name: Build APK with EAS
        run: |
          eas build -p android --profile preview --non-interactive

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-apk
          path: dist/**/*.apk
